name: genre_classification
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - pip=20.3.3
  - mlflow=2.2.2
  # - mlflow=1.14.1
  - hydra-core=1.0.6
  - pip:
      - wandb==0.13.9
      # - wandb==0.10.21
      # - numpy==1.23.4
      # - protobuf==3.19.0
      # - watchdog==0.10.4
      - hydra-joblib-launcher==1.1.2
